### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by sato-takehiro** [sato-takehiro/crypto-exchange#26]
■Webアプリの概要
最も安く仮想通貨を購入できる国内取引所を、ユーザ毎にリアイルタイムに表示する。

ユーザが購入したい仮想通貨/購入金額（JPY）を入力することで、Webアプリが取引所名を出力する。

作る理由は、証券会社と比べると、どの取引所が良いという総意は明確でなく、仮想通貨投資を始めにくい要因となっているため。

MVPリリース時は、ウォレット送金の有無/購入したい仮想通貨/購入金額（JPY）をユーザが入力し、最も手数料の安い取引所名を出力する機能を実装する。

本リリース時は、ユーザ登録することでLINE通知ができる機能を実装予定。

■ProjectsのURL
https://github.com/users/sato-takehiro/projects/3/views/1

■MVPリリースまで
- [ ] 環境構築
- [ ] デプロイ
- [ ] デプロイの自動化
- [ ] ヘッダー作成
- [ ] フッター作成
- [ ] トップページの作成
- [ ] 目的選択画面の作成
- [ ] 仮想通貨の名前/アイコンを取得しDBに保存
- [ ] 取引所診断ページの作成
- [ ] 取引所のHPから、購入/出金手数料を取得しDBに保存
- [ ] 取引所APIを用いて購入価格を取得する処理の作成
- [ ] 各種手数料/購入価格/ユーザの希望購入価格(JPY)から、各取引所の購入可能量を計算する処理の作成
- [ ] 取引所診断結果画面の作成

■MVP後
- [ ] 通知設定一覧ページの作成
- [ ] 通知設定作成ページの作成
- [ ] 通知設定編集ページの作成
- [ ] LINEログイン機能の作成
- [ ] LINE通知機能の作成
- [ ] お問い合わせページの作成
- [ ] 利用規約ページの作成
- [ ] プライバシーポリシーページの作成
- [ ] 独自ドメイン・SSL
- [ ] Rspec
- [ ] Google Search Console導入
- [ ] ファビコン
- [ ] 仮想通貨のアイコンをAmazon S3に保存
- [ ] Nuxt.js + Rails APIでアプリケーションを作成
- [ ] レスポンシブ対応

■MVPレビュー依頼予定日
予定日：2024年 9月 10日

**Comment by Tsuchiya2** [comment]
対応ありがとうございます。
ストーリーポイントを確認したところ、4ポイント以上のカードが存在するのを確認しました。
カリキュラムにもありましたとおり、ストーリーポイント3以下になるように細かくissue化してください。
細かくissue化することで、不明瞭な箇所、明瞭な箇所が可視化されることに加えて、進捗を感じられながら開発を進めることができます。
対応の上、再提出操作をお願いいたします。

**Comment by sato-takehiro** [comment]
お世話になります。
MVPリリースまでの、ストーリーポイント4以上になっていたIssueを3に分解・修正を行いました。
確認の程よろしくお願いいたします。

- [ ] [#14](https://github.com/sato-takehiro/crypto-exchange/issues/14)を、[#14](https://github.com/sato-takehiro/crypto-exchange/issues/14)と[#31](https://github.com/sato-takehiro/crypto-exchange/issues/31)と分解
- [ ] [#13](https://github.com/sato-takehiro/crypto-exchange/issues/13)を、[#13](https://github.com/sato-takehiro/crypto-exchange/issues/13)と[#30](https://github.com/sato-takehiro/crypto-exchange/issues/30)に分解
- [ ] [#16](https://github.com/sato-takehiro/crypto-exchange/issues/16)を、[#16](https://github.com/sato-takehiro/crypto-exchange/issues/16)と[#29](https://github.com/sato-takehiro/crypto-exchange/issues/29)に分解

**Comment by TakenakaEri** [comment]
ありがとうございます。LGTMです！

なお、タスクは上から順番に着手できるように並べ替えてある状態でしょうか？もし、順番が異なる部分がありましたら、変更しておいてください。

また、issueに関しては必要があれば追加してもらって大丈夫ですので、ご自身や他の人が見てもわかりやすいように、管理していただければと思います〜！

**Comment by sato-takehiro** [comment]
レビューありがとうございます！
承知いたしました！
